fix for journal.sh
Traceback (most recent call last):
  File "journal.py", line 5, in <module>
ImportError: /usr/lib/libpthread.so.0: version `GLIBC_PRIVATE' not found (required by ./backuplibs/librt.so.1)
[24416] Failed to execute script journal